### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by jakobkg** [Aidan-OS/Mochi40#1]
The `PCB/MX_Only.pretty` KiCad footprint library included in this repo appears to be from this project: https://github.com/ai03-2725/MX_Alps_Hybrid which is MIT licensed. The MIT license states that

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

However, the license and copyright notice does not seem to be present in the redistribution in this repo.

The same goes for the library `PCB/kbd.pretty` which seems to be a copy of the footprint library from https://github.com/foostan/kbd which is also MIT licensed, without the license or copyright notice included.

The nice!nano footprint in `PCB/nice-nano-kicad-master` appears to be this one: https://github.com/bstiq/nice-nano-kicad
That footprint is licensed under GPLv3, which states

> 4. Conveying Verbatim Copies.
> 
> You may convey verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice; keep intact all notices stating that this License and any non-permissive terms added in accord with section 7 apply to the code; keep intact all notices of the absence of any warranty; and give all recipients a copy of this License along with the Program.
> 
> You may charge any price or no price for each copy that you convey, and you may offer support or warranty protection for a fee.

GPLv3 also requires that any project using or redistributing GPLv3 components must also themselves be GPLv3 licensed, but this project is currently licensed under the MIT license which is incompatible.

Please consider replacing the footprint entirely with a part that's compatible with your chosen MIT license, or relicense your project under GPLv3 to keep using this particular part, as well as reinstating the license and copyright notices of the MIT licensed parts being used that are currently missing them. A potential solution would be to use git submodules to link back to the original projects rather than redistributing them, and changing some of the KiCad library paths to match.

**Comment by Aidan-OS** [comment]
Hi, thanks for pointing this out. I honestly didn't realize / remember that these got included. I'll get to fixing this.

**Comment by Aidan-OS** [comment]
I believe the linked pull request fixes. I went through and made sure to use submodules to link every package used (including others not mentioned). Thank you for showing me the Submodules feature, I have never used it before and it's quite neat.

Let me know if this is what you meant and I'll merge and close the issue.

**Comment by jakobkg** [comment]
That looks good at a glance, nice! :)
